"""
Django settings for enova_id project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-a8fzepjts#9i36tny87z59d=^5exmkk$a8a0^**vww145wwjce'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',  # カスタムアカウントアプリ
    'oauth2_provider',
    'rest_framework',
    'developer',  # ← ここに追加
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',  # セッション管理（必須）
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',  # 認証（必須）
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'accounts.middleware.SessionTrackingMiddleware',  # セッション追跡（AuthenticationMiddlewareの後）
]

ROOT_URLCONF = 'enova_id.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # テンプレートディレクトリを追加
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',  # 追加
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'enova_id.wsgi.application'


# Custom User Model
AUTH_USER_MODEL = 'accounts.CustomUser'


# Authentication URLs
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/accounts/login/'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ja'  # 日本語に変更
TIME_ZONE = 'Asia/Tokyo'  # 日本時間に変更
USE_I18N = True
USE_TZ = True


# Session Configuration
SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # データベースバックエンドを明示的に指定
SESSION_COOKIE_AGE = 1209600  # 2週間（秒）
SESSION_SAVE_EVERY_REQUEST = True  # リクエストごとにセッションを保存（セッション追跡に必須）
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # ブラウザを閉じてもセッションを保持
SESSION_COOKIE_NAME = 'enova_sessionid'  # セッションCookie名
SESSION_COOKIE_HTTPONLY = True  # JavaScriptからのアクセスを防ぐ
SESSION_COOKIE_SECURE = False  # 開発環境ではFalse、本番環境ではTrue
SESSION_COOKIE_SAMESITE = 'Lax'  # CSRF保護


# Messages Framework
from django.contrib.messages import constants as messages

MESSAGE_TAGS = {
    messages.DEBUG: 'secondary',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',
    messages.ERROR: 'danger',
}


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'  # 本番環境用
STATICFILES_DIRS = [
    BASE_DIR / 'static',  # 追加の静的ファイルディレクトリ
]


# Media files (User uploaded files)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'accounts': {  # accountsアプリのログ
            'handlers': ['console'],
            'level': 'DEBUG',  # デバッグレベル
            'propagate': False,
        },
    },
}

# WebAuthn (Passkey) 設定
WEBAUTHN_RP_NAME = "Enova ID"  # Relying Party名
WEBAUTHN_RP_ID = "localhost"  # 127.0.0.1は使用できない
WEBAUTHN_ALLOWED_ORIGINS = [
    "http://localhost:8000",
]
WEBAUTHN_USER_VERIFICATION = "preferred"  # "required", "preferred", "discouraged"
WEBAUTHN_AUTHENTICATOR_ATTACHMENT = None  # None, "platform", "cross-platform"


# OAuth2 Toolkit Settings
OAUTH2_PROVIDER = {
    'SCOPES': {
        'read': 'ユーザー情報の読み取り',
        'write': 'ユーザー情報の書き込み',
        'openid': 'OpenID識別子',
        'profile': 'プロフィール情報',
        'email': 'メールアドレス',
    },
    'ACCESS_TOKEN_EXPIRE_SECONDS': 36000,  # 10時間
    'REFRESH_TOKEN_EXPIRE_SECONDS': 2592000,  # 30日
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
    )
}

# Security Settings (開発環境用)
# 本番環境では以下を有効化してください
# SECURE_SSL_REDIRECT = True
# SESSION_COOKIE_SECURE = True
# CSRF_COOKIE_SECURE = True
# SECURE_BROWSER_XSS_FILTER = True
# SECURE_CONTENT_TYPE_NOSNIFF = True
# X_FRAME_OPTIONS = 'DENY'


# Email Configuration (開発環境用)
# 本番環境では実際のメールサーバー設定に変更してください
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # コンソールに出力
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'  # 本番環境
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'your-email@gmail.com'
# EMAIL_HOST_PASSWORD = 'your-password'
# DEFAULT_FROM_EMAIL = 'noreply@example.com'
