# Generated by Django 5.2.7 on 2025-10-31 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nickname',
            field=models.CharField(blank=True, help_text='表示用の名前（未設定の場合はユーザーIDが表示されます）', max_length=50, verbose_name='ニックネーム'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(help_text='ログイン用のID（英数字、@/./+/-/_のみ使用可能）', max_length=150, unique=True, verbose_name='ユーザーID'),
        ),
    ]
