# Generated by Django 5.2.7 on 2025-11-02 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_nickname_alter_customuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True, verbose_name='セッションキー')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IPアドレス')),
                ('user_agent', models.TextField(verbose_name='ユーザーエージェント')),
                ('device_type', models.CharField(max_length=50, verbose_name='デバイスタイプ')),
                ('device_name', models.CharField(max_length=200, verbose_name='デバイス名')),
                ('browser', models.CharField(max_length=100, verbose_name='ブラウザ')),
                ('os', models.CharField(max_length=100, verbose_name='OS')),
                ('location_city', models.CharField(blank=True, max_length=100, verbose_name='都市')),
                ('location_country', models.CharField(blank=True, max_length=100, verbose_name='国')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='最終アクティビティ')),
                ('is_current', models.BooleanField(default=False, verbose_name='現在のセッション')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'アクティブセッション',
                'verbose_name_plural': 'アクティブセッション',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IPアドレス')),
                ('user_agent', models.TextField(verbose_name='ユーザーエージェント')),
                ('device_type', models.CharField(max_length=50, verbose_name='デバイスタイプ')),
                ('device_name', models.CharField(max_length=200, verbose_name='デバイス名')),
                ('browser', models.CharField(max_length=100, verbose_name='ブラウザ')),
                ('os', models.CharField(max_length=100, verbose_name='OS')),
                ('location_city', models.CharField(blank=True, max_length=100, verbose_name='都市')),
                ('location_country', models.CharField(blank=True, max_length=100, verbose_name='国')),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失敗')], max_length=20, verbose_name='ステータス')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ログイン履歴',
                'verbose_name_plural': 'ログイン履歴',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WebAuthnChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge', models.TextField(verbose_name='チャレンジ')),
                ('challenge_type', models.CharField(choices=[('registration', '登録'), ('authentication', '認証')], max_length=20, verbose_name='タイプ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webauthn_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'WebAuthnチャレンジ',
                'verbose_name_plural': 'WebAuthnチャレンジ',
            },
        ),
        migrations.CreateModel(
            name='WebAuthnCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_id', models.TextField(unique=True, verbose_name='認証情報ID')),
                ('public_key', models.TextField(verbose_name='公開鍵')),
                ('sign_count', models.IntegerField(default=0, verbose_name='署名カウント')),
                ('device_name', models.CharField(max_length=200, verbose_name='デバイス名')),
                ('device_type', models.CharField(choices=[('platform', 'プラットフォーム認証'), ('cross-platform', 'クロスプラットフォーム')], max_length=50, verbose_name='デバイスタイプ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('last_used', models.DateTimeField(blank=True, null=True, verbose_name='最終使用日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webauthn_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'WebAuthn認証情報',
                'verbose_name_plural': 'WebAuthn認証情報',
                'ordering': ['-created_at'],
            },
        ),
    ]
