# Generated by Django 5.2.7 on 2025-11-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_webauthnchallenge_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webauthnchallenge',
            name='challenge_type',
            field=models.CharField(choices=[('registration', 'パスキー登録'), ('authentication', 'パスキー認証')], default='registration', max_length=20),
        ),
    ]
